import { Poppins } from 'next/font/google';
import { Sidebar } from "@/components/Sidebar"
import { Header } from '@/components/Header';
import '@/sass/globals.sass';
import 'animate.css';

const roboto = Poppins({
  weight: ["100", "300", "500", "700", "900"],
  subsets: ["latin"],
})


export const metadata = {
  title: 'Leeroy Garcia | Developer',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        <Header />
        <Sidebar />
        <main className='Content'>
          {children}
        </main>
      </body>
    </html>
  )
}
